# Generated by Django 6.0.1 on 2026-02-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
