# Generated by Django 6.0.1 on 2026-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publication_year', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('about_author', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
