# Generated by Django 6.0.1 on 2026-01-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_about_author_alter_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='about_author',
        ),
    ]
