# Generated by Django 6.0.1 on 2026-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
