# Generated by Django 6.0.1 on 2026-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='best_book',
            field=models.BooleanField(default=False),
        ),
    ]
